config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :news
  root 'inicios#index'
  resources :contacts
  resources :inicios
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: /\A[^@\s]+@[^@\s]+\z/i

  attribute :message

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      subject: "My Contact Form",
      to: "walter.camargo.gr@gmail.com",
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/news.rb
class News < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController  
  def index
    render new_contact_path	
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.deliver
      redirect_to root_path, notice: "Sua mensagem foi enviada com sucesso!"
    else
      flash[:error] = "Erro: Sua mensagem não foi enviada!"
      render new_contact_path
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/inicios_controller.rb
class IniciosController < ApplicationController
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @news = News.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/inicios_helper.rb
module IniciosHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/contacts/_form.html.erb
<!-- <%= form_for @contact, url: contacts_path do |f| %>
  <%= f.text_field :name, placeholder: "Nome" %>
  <%= f.text_field :email, placeholder: "E-mail" %>
  <%= f.text_field :message, placeholder: "Mensagem" %>
  <%= f.submit "Enviar Mensagem" %>
<% end %> -->

app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>
<div class="contato">
  <div class="faleconosco">
    <div class="conttitulo">
      <h1>Fale Conosco</h1>
    </div>
    <div class="contform">
      <%= form_for @contact do |f| %>
        <%= f.label :nome, class: "labelnome" %> <br>
        <%= f.text_field :name, required: true, class: "box" %> <br>

        <%= f.label :email, class: "labelnome" %> <br>
        <%= f.text_field :email, required: true, class: "box"  %> <br>

        <%= f.label :mensagem, class: "labelnome" %> <br>
        <%= f.text_area :message, as: :text, required: true, class: "boxtext"  %> <br>

        <%= f.submit "Enviar Mensagem", class: "button" %> <br>
      <% end %>
    </div>
  </div>
  
  <div class="contendereco">
    <h2 class="estamosaqui">Estamos aqui!</h2>
    <div class="horariodefunc">
      <p>Horário de Funcionamento (seg à sex)</p>
      <p>Das 08:00 às 12:00 e das 13:00 as 17:00</p>
      <p>Rua Benjamin Constante, 245</p>
      <p>Ibiúna, Centro - São Paulo</p>
      <p>CEP 18.150-000</p>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3654.6136306302797!2d-47.22332618506279!3d-23.65400407090501!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94cf7698837f1d5b%3A0xb28620b42e82aad9!2sR.%20Benjamin%20Constant%2C%20245%20-%20Centro%2C%20Ibi%C3%BAna%20-%20SP%2C%2018150-000!5e0!3m2!1spt-PT!2sbr!4v1604889790586!5m2!1spt-PT!2sbr" width="300" height="170" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
  </div>
</div>

app/views/contatos/create.html.erb
<div class="contform">
  <h1>AGRADECEMOS O CONTATO</h1>
</div>

app/views/contatos/new.html.erb
<div class="contato">
  <div class="faleconosco">
    <div class="conttitulo">
      <h1>Fale Conosco</h1>
    </div>
    <div class="contform">
      <%= form_for @contato do |f| %>
        <%= f.label :nome, class: "labelnome" %> <br>
        <%= f.text_field :name, required: true, class: "box" %> <br>

        <%= f.label :email, class: "labelnome" %> <br>
        <%= f.text_field :email, required: true, class: "box"  %> <br>

        <%= f.label :mensagem, class: "labelnome" %> <br>
        <%= f.text_area :message, as: :text, required: true, class: "boxtext"  %> <br>

        <%= f.submit "Enviar Mensagem", class: "button" %> <br>
      <% end %>
    </div>
  </div>
  
  <div class="contendereco">
    <h2 class="estamosaqui">Estamos aqui!</h2>
    <div class="horariodefunc">
      <p>Horário de Funcionamento (seg à sex)</p>
      <p>Das 08:00 às 12:00 e das 13:00 as 17:00</p>
      <p>Rua Benjamin Constante, 245</p>
      <p>Ibiúna, Centro - São Paulo</p>
      <p>CEP 18.150-000</p>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3654.6136306302797!2d-47.22332618506279!3d-23.65400407090501!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94cf7698837f1d5b%3A0xb28620b42e82aad9!2sR.%20Benjamin%20Constant%2C%20245%20-%20Centro%2C%20Ibi%C3%BAna%20-%20SP%2C%2018150-000!5e0!3m2!1spt-PT!2sbr!4v1604889790586!5m2!1spt-PT!2sbr" width="300" height="170" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
  </div>
</div>

app/views/inicios/index.html.erb
<div class="inicio">
  <div class="slider">
    <%= image_tag '1.jpg', class:"foto" %>
    <%= image_tag '2.jpg', class:"foto" %>
    <%= image_tag '3.jpg', class:"foto" %>
  </div>

  <div class="contribuicoes">
    <div class="sociocontri">
      <%= image_tag "socio.jpg", class: 'imagemsocio' %>
      <div class="dadossocio">
        <h2>Sócio Contribuinte APAE - Ibiúna</h2>
        </p>CNPJ: 34.037.148/0001-12
        </p>Rua Benjamim Constant, n 245 - Centro 
        </p>Tel: (15) 3248-2444
        </p>Tel celular: (15) 99671-3142
      </div>
    </div>
    <a target="_blank" rel="noopener noreferrer" href="https://docs.google.com/forms/d/e/1FAIpQLSfZ_lyJ0I4zylQS9OHHnVyt_8VC-ELAoTrkLCo4P9zUqKHBQQ/viewform?fbclid=IwAR11fBV80pwv4bSfIVFXVSMuF8eJLqd4X4wtwJ8dJy4dM0u_TPxqP8ZWgjU">
      <div class="containerdonate">
          <%= image_tag "donate.jpg", class:'donateimg' %>
          <div class="donatetext">
            <p> <i class="fas fa-hand-holding-heart"></i> </p>
            <small> FAÇA SUA </small>
            <p> <b>DOAÇÃO</b> </p>
          </div>
      </div>
    </a>
  </div>
  
  <div class="inicioag">
    <h1> Atuamos nas áreas de </h1>
    <div class="areasdeat">
      <div class="educacao">
        <p>Educação</p>
        <i class="fas fa-pencil-alt"></i>
      </div>
      <div class="familia">
        <p>Assistência</p>
        <p>Familiar</p>
        <i class="fas fa-home"></i>
      </div>
      <div class="saude">
        <p>Saúde Mental</p>
        <i class="fas fa-heartbeat"></i>
      </div>
    </div>
  </div>

  <div class="parceiros">
    <div class="containerparc">
      <input type="radio" name="images" class="i1" id="i1" checked>
      <input type="radio" name="images" class="i2" id="i2">
      <input type="radio" name="images" class="i3" id="i3">
      <div class="slider-img img-1" id="img1">
        <%= image_tag "nestle.png", class: "imagens n1" %>
        <label for="i3" class="pre"></label>
        <label for="i2" class="next"></label>
      </div>
      <div class="slider-img img-2" id="img2">
        <%= image_tag "apaeibiuna.jpg", class: "imagens n2" %>
        <label for="i1" class="pre"></label>
        <label for="i3" class="next"></label>
      </div>
      <div class="slider-img img-3" id="img3">
        <%= image_tag "socio.jpg", class: "imagens n3" %>
        <label for="i2" class="pre"></label>
        <label for="i1" class="next"></label>
      </div>

      <div class="nav">
       <label class="dots dot1" for="i1"></label>
       <label class="dots dot2" for="i2"></label>
       <label class="dots dot3" for="i3"></label>
      </div>

      <div class="automatic-nav">
        <label class="dots autodot1" for="i1"></label>
        <label class="dots autodot2" for="i2"></label>
        <label class="dots autodot3" for="i3"></label>
      </div>
    </div>
  </div>

  <div class="inicioeventos">
    <div class="eventotit">
      <h1> PRÓXIMOS EVENTOS </h1>
    </div>
    <div class="agendaeventos">
      <h2>
        ...
      </h2>
    </div>
  </div>

  <div class="inicioacessos">
    <div class="qdoacao">
      <div class="titdoacao">
        <h2> INFORMAÇÃO </h2>
        <small>para doações <i class="fas fa-heart"></i></small>
      </div>
      <div class="infodoacao">
        <p>CNPJ: 34.037.148/0001-12</p>
        <p> Banco do Brasil </p>
        <p>AGÊNCIA: 0825-7</p>
        <p>Conta Corrente: 39565-0</p>
        <p>Gratidão por qualquer valor</p>
      </div>
    </div>

    <div class="fbfbfb">
      <head>
        <div id="fb-root"></div>
        <script async defer crossorigin="anonymous" src="https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v8.0" nonce="kZnCPTtl"></script>
      </head>
      <div class="facebookapae">
        <div class="fb-page" data-href="https://www.facebook.com/apaeibiunasp" data-tabs="timeline" data-width="250" data-height="400" data-small-header="false" data-adapt-container-width="false" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/apaeibiunasp" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/apaeibiunasp">APAE Ibiúna SP</a></blockquote></div>
      </div>
    </div>

    <div class="googlemaps">
      <div class="googletitulo">
        <p> ESTAMOS <strong><p>AQUI</strong> </p>
      </div>
      <div class="googleinfo">
        <p>Rua Benjamin Constante, 245</p>
        <p>Ibiúna, Centro - São Paulo</p>
        <p>CEP 18.150-000</p>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3654.6136306302797!2d-47.22332618506279!3d-23.65400407090501!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94cf7698837f1d5b%3A0xb28620b42e82aad9!2sR.%20Benjamin%20Constant%2C%20245%20-%20Centro%2C%20Ibi%C3%BAna%20-%20SP%2C%2018150-000!5e0!3m2!1spt-PT!2sbr!4v1604889790586!5m2!1spt-PT!2sbr" width="250" height="170" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>    </div>
      </div>
    </div>
    
  </div>
</div>

<script>
  var counter = 1;
  setInterval(function(){
    document.getElementById('i' + counter).checked = true
    counter++
    if(counter > 3){
      counter = 1
    }
  }, 4000)
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apae Ibiúna</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=ABeeZee&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@900&family=Poppins:wght@900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,900;1,300&display=swap" rel="stylesheet">

  </head>

  <body>
    <header>
      <div class="logoapae1">
        <div class="superior">
          <div class="apaeoriginal">
            <a target="_blank" rel="noopener noreferrer" href="https://apae.com.br/">
              <%= image_tag "apaem.svg", style: 'float:left; margin-top:10px;height:70px;' %>
              <span class="a-apaebrasil">APAE BRASIL </span>
            </a>
          </div>
          <div class="sociocont">
            <%= image_tag "apaeibiuna.jpg", style: 'float:left;height:70px;' %>
            <a target="_blank" rel="noopener noreferrer" class="doacao" href="https://docs.google.com/forms/d/e/1FAIpQLSfZ_lyJ0I4zylQS9OHHnVyt_8VC-ELAoTrkLCo4P9zUqKHBQQ/viewform?fbclid=IwAR11fBV80pwv4bSfIVFXVSMuF8eJLqd4X4wtwJ8dJy4dM0u_TPxqP8ZWgjU">
              <b> CONTRIBUA <i class='fas fa-hand-holding-heart'></i> </b>
            </a>
          </div>
        </div>
        <div class="navegador">
          <nav role="navigation" class="navegador1">
            <ul class="navlist">
              <li class="item item1"><a href="<%= inicios_path %>">Início</a></li>
              <li class="item"><a>APAE</a></li>
              <li class="item"><a>Bazar APAE</a></li>
              <li class="item"><a href="<%= news_index_path	 %>">Notícias</a></li>
              <li class="item"><a>Parceiros</a></li>
              <li class="item"><a>Doações</a></li>
              <li class="item"><a href="<%= new_contact_path %>">Contato</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

    <main class="site-content">
      <section class="main-content">
        <%= yield %>
      </section>
    </main>

    <footer>
      <div class="container">
        <div class="contato">
        <a class="telefone">
          <i class="fas fa-phone"></i>
          <span class="telemail"> (15) 3248-2444</span>
          <i class="fas fa-envelope-open-text"></i>
          <span class="email">ibiunaapae@gmail.com</span>
          <i class="fas fa-map-marker-alt"></i>
          <span class="endereco"> Rua Benjamin Constante, 245 - Centro, Ibiúna - SP, 18150-000 </span>
          <a target="_blank" rel="noopener noreferrer" class="facebookbtn" href="https://www.facebook.com/apaeibiunasp">
          <i class="fab fa-facebook-square "></i>
          </a>
        </div>
          <div class="apaeibiunaimg">
            <%= image_tag "logo_apae.png", style: 'float:left; margin-top:10px' %>
            <a class="meulink" href="https://www.linkedin.com/in/wowtz/"> Produzidor por Walter de C Grangeiro </a>
          </div>
        </a>
      </div>
    </footer>
  </body>
</html>

app/views/news/index.html.erb
<div class="noticias">
  <div class="noticiastit">
    <h1> NOTÍCIAS </h1>
  </div>
  
  <div class="noticiasnot">
    <% @news.each do |news| %>
      <div class="titulonot">
        <b><%= news.title %></b>
      </div>
        <p> <%= news.description %> </p>
      <small>Data de atualização: <%= news.created_at %></small>
    
    <% end %>
  </div>
</div>